refactor logging
cisco-open/nasp-kernel-module pull request #109
Opened 2023-11-14 21:56 UTC by waynz0r

## Description

change logging strategy to use pr_debug for most places and use dynamic debug if needed

## Type of Change

- [x] Refactor

2023-11-16 08:02 UTC, bonifaido requested changes
I would add some instructions to the README how to extract those logs on lower log levels.

2023-11-16 13:31 UTC, baluchicken commented on csr.c
> +    }
```suggestion
    } \
```

2023-11-16 13:36 UTC, baluchicken commented on device_driver.c
> +            pr_info("load module # name[%s]", name);
```suggestion
            pr_debug("load module # name[%s]", name);
```

2023-11-16 13:48 UTC, baluchicken commented on device_driver.c
> +                pr_info("setting default module entrypoint # entrypoint[%s]", DEFAULT_MODULE_ENTRYPOINT);
```suggestion
                pr_debug("setting default module entrypoint # entrypoint[%s]", DEFAULT_MODULE_ENTRYPOINT);
```

2023-11-16 13:48 UTC, baluchicken commented on device_driver.c
> +            pr_info("reseting vm");
```suggestion
            pr_debug("reseting vm");
```

2023-11-16 13:48 UTC, baluchicken commented on device_driver.c
> +            pr_info("load rules");
```suggestion
            pr_debug("load rules");
```

2023-11-16 13:48 UTC, baluchicken commented on device_driver.c
> +            pr_info("load config");
```suggestion
            pr_debug("load config");
```

2023-11-16 13:48 UTC, baluchicken commented on device_driver.c
> +            pr_info("load sd info");
```suggestion
            pr_debug("load sd info");
```

2023-11-16 13:48 UTC, baluchicken commented on device_driver.c
> +    pr_info("communcation device closed # command[%s]", current->comm);
```suggestion
    pr_debug("communcation device closed # command[%s]", current->comm);
```

2023-11-16 13:48 UTC, baluchicken commented on main.c
> +    pr_info("module loaded at 0x%p running on %d CPUs", nasp_init, nr_cpu_ids);
```suggestion
    pr_debug("module loaded at 0x%p running on %d CPUs", nasp_init, nr_cpu_ids);
```

2023-11-16 13:48 UTC, baluchicken commented on opa.c
> +                pr_warn("unsupported builtin function # name[%s]", name);
```suggestion
                pr_debug("unsupported builtin function # name[%s]", name);
```

2023-11-16 13:48 UTC, baluchicken commented on opa.c
> +        pr_warn("opa socket policy module not loaded: eval always evaluates to NULL");
```suggestion
        pr_debug("opa socket policy module not loaded: eval always evaluates to NULL");
```

2023-11-16 13:48 UTC, baluchicken commented on socket.c
> +		pr_warn("recvmsg copy_to_iter copied less than requested");
```suggestion
		pr_debug("recvmsg copy_to_iter copied less than requested");
```

2023-11-16 13:48 UTC, baluchicken commented on socket.c
> +		pr_warn("configure kTLS error: only ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 cipher suite is supported # requested_suite[%x]", params->cipher_suite);
```suggestion
		pr_debug("configure kTLS error: only ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 cipher suite is supported # requested_suite[%x]", params->cipher_suite);
```

2023-11-16 13:48 UTC, baluchicken commented on socket.c
> +		pr_warn("remove invalid certificate from cache");
```suggestion
		pr_debug("remove invalid certificate from cache");
```

2023-11-16 13:48 UTC, baluchicken commented on socket.c
> +	pr_info("socket support loaded");
```suggestion
	pr_debug("socket support loaded");
```

2023-11-16 13:48 UTC, baluchicken commented on socket.c
> +	pr_info("socket support unloaded");
```suggestion
	pr_debug("socket support unloaded");
```

2023-11-16 13:48 UTC, baluchicken commented on wasm.c
> +        pr_info("create vm # cpu[%d]", cpu);
```suggestion
        pr_debug("create vm # cpu[%d]", cpu);
```

2023-11-16 13:48 UTC, baluchicken commented on wasm.c
> +            pr_info("destroy vm # cpu[%d]", cpu);
```suggestion
            pr_debug("destroy vm # cpu[%d]", cpu);
```

2023-11-24 20:10 UTC, bonifaido approved these changes

2023-11-24 21:08 UTC, merged