Workload attestation
cisco-open/nasp-kernel-module pull request #86
Opened 2023-10-18 10:11 UTC by waynz0r

## Description

Please provide a meaningful description of what this change will do, or is for. Bonus points for including links to
related issues, other PRs, or technical references.

Note that by _not_ including a description, you are asking reviewers to do extra work to understand the context of this
change, which may lead to your PR taking much longer to review, or result in it not being reviewed at all.

## Type of Change

- [ ] Bug Fix
- [ ] New Feature
- [ ] Breaking Change
- [ ] Refactor
- [ ] Documentation
- [ ] Other (please describe)

## Checklist

- [ ] I have read the [contributing guidelines](/CONTRIBUTING.md)
- [ ] Existing issues have been referenced (where applicable)
- [ ] I have verified this change is not present in other open pull requests
- [ ] Functionality is documented
- [ ] All code style checks pass
- [ ] New code contribution is covered by automated tests
- [ ] All new and existing tests pass

2023-10-18 13:58 UTC, baluchicken requested changes

2023-10-18 13:58 UTC, baluchicken commented on commands.c
> +    }
I would avoid the strcpy function, instead I would use `cont char* ipformat`. and simply update the pointer value inside the if.

2023-10-18 13:58 UTC, baluchicken commented on commands.c
> +    JSON_Object *root_object = json_value_get_object(root_value);
We must check if these return values are NULLs or not.

2023-10-18 13:58 UTC, baluchicken commented on commands.c
> +    json_value_free(root_value);
This json_value_free function name is misleading for me. I would add a command that this function also frees the root_object field.

2023-10-18 13:58 UTC, baluchicken commented on commands.c
>      JSON_Value *root_value = json_value_init_object();
The NULL check should apply here as well.

2023-10-18 13:58 UTC, baluchicken commented on commands.c
The whole file lacks the NULL check for 
```
JSON_Value *root_value = json_value_init_object();
 JSON_Object *root_object = json_value_get_object(root_value);
  ```

2023-10-18 13:58 UTC, baluchicken commented on device_driver.c
> +        json = json_parse_string(data);
This can be NULL, we must check this to avoid NULL pointer exception.

2023-10-18 13:58 UTC, baluchicken commented on device_driver.c
> +            char *decoded = kzalloc(strlen(code) * 2, GFP_KERNEL);
This field leaks memory if no error happens. We should kfree even when the load module succeeds.

2023-10-18 13:58 UTC, baluchicken commented on device_driver.c
> +            char *decoded = kzalloc(strlen(code) * 2, GFP_KERNEL);
We should kfree decoded in case of length <0

2023-10-18 13:58 UTC, baluchicken commented on device_driver.c
> +            load_opa_data(strdup(decoded));
Why do we need to strdup the decoded data here?

2023-10-18 13:58 UTC, baluchicken commented on device_driver.c
> +    kfree(data);
I think this is a bad idea to free data that comes as a function parameter.

2023-10-18 13:58 UTC, baluchicken commented on device_driver.c
> +    char uuid[UUID_SIZE + 21];
What is 21? Please create a constant with a meaningful name.

2023-10-18 13:58 UTC, baluchicken commented on device_driver.c
> +        int status = parse_json_from_buffer(strdup(device_buffer));
If we remove the kfree(data) from the parse_json_from_buffer function this strdup is not needed.

2023-10-18 13:58 UTC, baluchicken commented on device_driver.c
> -            return -1;
If I understand it correctly. Removing this return here means we are unable to parse the JSON from the buffer but it is fine we are moving forward and removing the failed data from the buffer and moving forward. Is this what is happening here?

2023-10-18 14:29 UTC, baluchicken requested changes

2023-10-18 16:35 UTC, baluchicken commented on opa.c
> +            ret.uri = strndup("spiffe://unspecified", 20);
After further investigation, I saw why the strndup needed.

2023-10-19 08:07 UTC, baluchicken commented on device_driver.c
> -            return -1;
After further discussion returning -1 is also a bad idea. It put the agent into an unrecoverable state.

2023-10-19 13:48 UTC, baluchicken commented on socket.c
> +		pr_err("nasp: connect failed to send attest command: %s", answer->error);
Same as above, shouldn't we goto error in this case?

2023-10-19 13:48 UTC, baluchicken commented on tls.c
> +        return 62;
What is 62?

2023-10-19 14:03 UTC, baluchicken commented on socket.c
> +		pr_err("nasp: accept failed to send attest command: %s", answer->error);
This is a design decision made by us to fall through without mtls when the attestation failes for some reason.

2023-10-19 14:03 UTC, baluchicken commented on socket.c
> +		pr_err("nasp: connect failed to send attest command: %s", answer->error);
This is a design decision made by us to fall through without mtls when the attestation fails for some reason.

2023-10-19 14:04 UTC, baluchicken commented on tls.c
> +        return 62;
This is an error code:
/** \brief X.509 status: chain could not be linked to a trust anchor. */
#define BR_ERR_X509_NOT_TRUSTED           62

2023-10-19 14:31 UTC, baluchicken submitted a review, later dismissed

2023-10-20 09:43 UTC, bonifaido submitted a review, later dismissed

2023-10-24 08:26 UTC, bonifaido approved these changes

2023-10-24 10:16 UTC, merged